apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: poc-statefun
  namespace: statefun
spec:
  image: apache/flink-statefun:3.2.0

  flinkVersion: v1_14
  flinkConfiguration:
    jobmanager.rpc.address: statefun-master
    taskmanager.numberOfTaskSlots: 1
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    classloader.parent-first-patterns.additional: org.apache.flink.statefun;org.apache.kafka;com.google.protobuf
    state.checkpoints.dir: s3://my-checkpoint-bucket
    state.backend: rocksdb
    state.backend.rocksdb.timer-service.factory: ROCKSDB
    state.backend.incremental: true
    execution.checkpointing.interval: 10sec
    execution.checkpointing.mode: EXACTLY_ONCE
    restart-strategy: fixed-delay
    restart-strategy.fixed-delay.attempts: 2147483647
    restart-strategy.fixed-delay.delay: 1sec
    jobmanager.memory.process.size: 1g
    taskmanager.memory.process.size: 1g
    parallelism.default: 3
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: poc-apache-flink-job
    spec:
      containers:
        # Do not change the main container name
        - name: flink-main-container
          volumeMounts:
            - mountPath: /opt/flink/usrconfig
              name: flink-usrconfig
        # Sample sidecar container
      volumes:
        - name: flink-usrconfig
          configMap:
            name: poc-apache-flink-job-config
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/poc-apache-flink-job.jar
    parallelism: 2
    upgradeMode: stateless
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-apache-flink-job-config
  namespace: default
data:
  kafka.properties: |
    bootstrap.servers=kafka.confluent:9092
  job.properties: |
    input.topic=words_in
    output.topic=wordcount
    group_id=wordcount