apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: simple-stream-job
spec:
  image: localhost:5001/simple-stream-job:latest
  imagePullPolicy: Always
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
#    high-availability.type: kubernetes
#    high-availability.storageDir: s3://flink/recovery
#    s3.access.key: "minio"
#    s3.secret.key: "minio123"
#    s3.endpoint: "http://myminio-hl.minio-tenant:9000"
  serviceAccount: flink
  ingress:
    template: "{{name}}.{{namespace}}.localtest.me"
    className: "nginx"
    #annotations:
    #  nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: simple-stream-job
    spec:
      containers:
        # Do not change the main container name
        - name: flink-main-container
          volumeMounts:
            - mountPath: /opt/flink/usrconfig
              name: flink-usrconfig
        # Sample sidecar container
      volumes:
        - name: flink-usrconfig
          configMap:
            name: simple-stream-job-config
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/flink-job.jar
    parallelism: 2
    upgradeMode: stateless
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-stream-job-config
  namespace: default
data:
  kafka.properties: |
    bootstrap.servers=kafka.confluent:9092
  job.properties: |
    input.topic=words_in
    output.topic=wordcount
    group_id=wordcount