apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: simple-batch-job
spec:
  image: localhost:5001/simple-batch-job:latest
  imagePullPolicy: Always
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    # s3.access.key: ""
    # s3.secret.key: ""
    # s3.endpoint: ""
    # s3.proxy.host: ""
    # s3.proxy.port: ""
  serviceAccount: flink
  ingress:
    template: "{{name}}.{{namespace}}.localtest.me"
    className: "nginx"
    #annotations:
    #  nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/flink-job.jar
    parallelism: 2
    upgradeMode: stateless
    args:
      - "--input=s3://myminio-hl.minio-tenant:9000/testdata/demo-bucket/in/largefile.txt"
      - "--output=s3://myminio-hl.minio-tenant:9000/testdata/demo-bucket/out/largefile.csv"
