apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ include "datagen.fullname" . }}
spec:
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  #    high-availability.type: kubernetes
  #    high-availability.storageDir: s3://flink/recovery
  #    s3.access.key: "minio"
  #    s3.secret.key: "minio123"
  #    s3.endpoint: "http://myminio-hl.minio-tenant:9000"
  serviceAccount: {{ .Values.serviceAccount.name }}
  ingress:
    template: "{{ "{{" }}name{{ "}}" }}.{{ "{{" }}namespace{{ "}}" }}.localtest.me"
    className: "nginx"
    #annotations:
    #  nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: {{ include "datagen.fullname" . }}
    spec:
      containers:
        # Do not change the main container name
        - name: flink-main-container
          volumeMounts:
            - mountPath: /opt/flink/usrconfig
              name: flink-usrconfig
        # Sample sidecar container
      volumes:
        - name: flink-usrconfig
          configMap:
            name: {{ include "datagen.fullname" . }}-config
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/flink-job.jar
    args: [ "/opt/flink/usrconfig/flink.sql" ]
    parallelism: 2
    upgradeMode: stateless
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datagen.fullname" . }}-config
data:
  {{- $files := .Files }}
  {{- range tuple "flink.sql" }}
  {{ . }}: |-
{{ $files.Get . | nindent 4 }}
  {{- end }}