apiVersion: skaffold/v3
kind: Config
metadata:
  name: sample-scenario-datagen
build:
#  insecureRegistries:
#    - localhost:5001
  local:
    push: true
  artifacts:
    - image: sample-scenario-datagen
      #docker:
      #  dockerfile: Dockerfile
      custom:
        # environment variable $IMG2 will be set to the build of image2
        buildCommand: |
          docker build . -f Dockerfile --tag=$IMAGE
          docker image push $IMAGE
deploy:
  helm:
#    flags:
#      global: [--debug]
    releases:
    - name: datagen
      chartPath: helm
      
      #wait: true
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_sample_scenario_datagen}}"
        image.tag: "{{.IMAGE_TAG_sample_scenario_datagen}}@{{.IMAGE_DIGEST_sample_scenario_datagen}}"
      setValues:
        image.pullPolicy: "IfNotPresent"
