# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

checkpoint:
  dir: file:///checkpoint-dir
  mode: EXACTLY_ONCE
  interval: 10sec

ha:
  id: simple-statefun-app-application
  dir: file:///ha-ir

master:
  name: simple-statefun-app-master
  image: localhost:5001/simple-statefun-app:latest # replace with your image
  jvm_mem: 1g
  container_mem: 1.5Gi

worker:
  name: simple-statefun-app-worker
  image: localhost:5001/simple-statefun-app:latest # replace with your image
  jvm_mem: 1g
  container_mem: 1.5Gi
  replicas: 1

ingress:
  url: "simple-statefun-app.default.localtest.me"
  className: "nginx"

kafka:
  broker: kafka.confluent:9092
  topics:
    message: