apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
  namespace: mongodb
  labels:
    app: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-user
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-user
                  key: password
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://user:password@mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017"
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "user"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express
  namespace: mongodb
spec:
  selector:
    app: mongodb-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-express
  namespace: mongodb
spec:
  ingressClassName: nginx
  rules:
    - host: express.mongodb.localtest.me
      http:
        paths:
          - backend:
              service:
                name: mongodb-express
                port:
                  number: 8081
            pathType: ImplementationSpecific