@startuml

database claims_db as "Claims DB\n<<Mongo Db>>>"
database policies_db as "Policies DB\n<<Mongo Db>>>"

queue customers_topic as "customers\n<<Kafka Topic>>"
queue policies_topic as "policies\n<<Kafka Topic>>"
queue claims_topic as "claims\n<<Kafka Topic>>"

component weekly_report_batch as "Weekly Report\n<<Flink Batch>>"

claims_db ---> claims_topic
policies_db ---> policies_topic

claims_topic ---> weekly_report_batch
policies_topic ---> weekly_report_batch
customers_topic ---> weekly_report_batch

file weekly_report_file as "Weekly Report File\n<<CSV>>"

weekly_report_batch -> weekly_report_file

component fraud_detection as "Fraud Detection\n<<Flink Stream>>"

claims_topic ---> fraud_detection
policies_topic ---> fraud_detection
customers_topic ---> fraud_detection

database results_db as "Results DB\n<<Apache Druid>>"

fraud_detection -> results_db

component live_report as "Live Report\n<<Flink SQL>>"

claims_topic ---> live_report
policies_topic ---> live_report
customers_topic ---> live_report

live_report -> results_db

weekly_report_batch -left[hidden]- fraud_detection
fraud_detection -left[hidden]- live_report

fraud_detection -down[hidden]- results_db
weekly_report_batch -down[hidden]- weekly_report_file
@enduml
