apiVersion: skaffold/v3
kind: Config
metadata:
  name: sample-scenario
build:
  local:
    concurrency: 0 #builds all artifacts parallely
requires:
  - path: ./env
  - path: ./datagen
  - path: ./live-report