# Default values for lab-catalog-kafka-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
schema_registry:
  enabled: true
  namespace: confluent
  group_id: cg.dev.lab.schemaregistry
  kafkastore:
    topic_name: dev.lab.schemaregistry.schemas
    topic_replication_factor: 3
    group_id: cg.dev.lab.schemaregistry.kafkastore
  url: http://schemaregistry-0-internal:8081
  authentication:
    type: basic
    secret: cloud-sr-access

kafka_connect:
  namespace: confluent
  group_id: connect-cg.dev.lab.catalog
  offset_storage:
    topic_name: dev.lab.connect-offsets
    topic_replication_factor: 3
  config_storage:
    topic_name: dev.lab.connect-configs
    topic_replication_factor: 3
  status_storage:
    topic_name: dev.lab.connect-status
    topic_replication_factor: 3
  plugins:
    locationType: confluentHub
    confluentHub:
      - name: kafka-connect-mongodb
        owner: mongodb
        version: "1.9.1"

kafka:
  bootstrap_servers: localhost:9092
  schema_registry_url: http://localhost:8081
  authentication:
    enabled: false
    type: plain
    secret: cloud-plain

output:
  topic: policies
  schema:
    namespace: com.policies

mongodb:
  host: localhost
  port: 27017
  database: db
  authDatabase: admin
  username: user
  password: password
  collection: claims