# Default values for lab-catalog-kafka-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
schema_registry:
  enabled: true
  namespace: confluent
  group_id: cg.dev.lab.schemaregistry
  kafkastore:
    topic_name: dev.lab.schemaregistry.schemas
    topic_replication_factor: 3
    group_id: cg.dev.lab.schemaregistry.kafkastore
  url: http://schemaregistry-0-internal:8081
  authentication:
    enabled: false
    type: basic
    secret: cloud-sr-access

kafka_connect:
  create: true
  namespace: confluent
  group_id: connect-cg.dev.lab.catalog
  offset_storage:
    topic_name: connect-offsets
    replication_factor: 1
    partitions: 5
  config_storage:
    topic_name: connect-configs
    replication_factor: 1
  status_storage:
    topic_name: connect-status
    replication_factor: 1
    partitions: 5
  plugins:
    locationType: confluentHub
    confluentHub:
      - name: kafka-connect-mongodb
        owner: mongodb
        version: "1.9.1"

kafka:
  bootstrap_servers: localhost:9092
  tls_enabled: false
  schema_registry_url: http://localhost:8081
  authentication:
    enabled: false
    type: plain
    secret: cloud-plain

output:
  topic: policies
  schema: "{\"namespace\": \"com.github.scalvetr.poc.flink.policy.model\",\"name\": \"Policy\",\"type\": \"record\",\"fields\": [{\"name\": \"policyId\",\"type\": \"string\"},{\"name\": \"customerId\",\"type\": \"string\"},{\"name\": \"title\",\"type\": \"string\"},{\"name\": \"creationTimestamp\",\"type\": \"long\",\"logicalType\": \"timestamp-millis\"}]}"

mongodb:
  host: localhost
  port: 27017
  database: db
  authDatabase: admin
  username: user
  password: password
  collection: policies