apiVersion: skaffold/v3
kind: Config
metadata:
  name: sample-scenario-datagen
build:
#  insecureRegistries:
#    - localhost:5001
  local:
    push: true
  artifacts:
    - image: sampleScenarioDatagen
      #docker:
      #  dockerfile: Dockerfile
      custom:
        # environment variable $IMG2 will be set to the build of image2
        buildCommand: |
          # Option: Staged
          #docker build . -f staged.Dockerfile --tag=$IMAGE
          
          # Option: maven outside docker
          ./mvnw clean package
          docker build . -f Dockerfile --tag=$IMAGE
          docker image push $IMAGE
deploy:
  helm:
#    flags:
#      global: [--debug]
    releases:
    - name: datagen
      chartPath: helm
      
      #wait: true
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_sampleScenarioDatagen}}"
        image.tag: "{{.IMAGE_TAG_sampleScenarioDatagen}}@{{.IMAGE_DIGEST_sampleScenarioDatagen}}"
      setValues:
        image.pullPolicy: "IfNotPresent"
