apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: sample-scenario-env
build:
  local:
    concurrency: 0 #builds all artifacts parallely
deploy:
  helm:
    releases:
      # https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/README.md
      - name: community-operator
        repo: https://mongodb.github.io/helm-charts
        remoteChart: community-operator
        namespace: mongodb
        createNamespace: true
        setValues:
          image.pullPolicy: "IfNotPresent"
      - name: sample-scenario-env
        chartPath: helm
        setValues:
          mongodb.database: db
          mongodb.authenticationDatabase: admin
          mongodb.username: user
          mongodb.password: password
          kafka.topics.customers: customers
