apiVersion: skaffold/v3
kind: Config
metadata:
  name: sample-scenario-env
build:
  local:
    concurrency: 0 #builds all artifacts parallely
deploy:
  helm:
    releases:
      # https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/README.md
      - name: community-operator
        remoteChart: mongodb/community-operator
        namespace: mongodb
        setValues:
          image.pullPolicy: "IfNotPresent"
      - name: env
        chartPath: helm

        #wait: true
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_sample_scenario_live_report}}"
          image.tag: "{{.IMAGE_TAG_sample_scenario_live_report}}@{{.IMAGE_DIGEST_sample_scenario_live_report}}"
        setValues:
          image.pullPolicy: "IfNotPresent"
