apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: sample-scenario-env
build:
  local:
    concurrency: 0 #builds all artifacts parallely
deploy:
  helm:
    releases:
      - name: sample-scenario-env
        chartPath: helm
        namespace: mongodb
        createNamespace: true
        setValues:
          mongodb.database: db
          mongodb.authenticationDatabase: admin
          mongodb.username: user
          mongodb.password: password
          kafka.topics.customers: customers
