apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: poc-apache-flink-job
spec:
  image: kind-registry:5000/poc-apache-flink-job:latest
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/poc-apache-flink-job.jar
    parallelism: 2
    upgradeMode: stateless