apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.functions.shoppingcart.name }}
  labels:
    app: {{ include "deployment.fullname" . }}
    component: {{ .Values.functions.shoppingcart.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "deployment.fullname" . }}
      component: {{ .Values.functions.shoppingcart.name }}
  template:
    metadata:
      labels:
        app: {{ include "deployment.fullname" . }}
        component: {{ .Values.functions.shoppingcart.name }}
    spec:
      containers:
        - name: main
          image: {{ .Values.functions.shoppingcart.image }}
          resources:
            requests:
              memory: "{{ .Values.functions.shoppingcart.container_mem }}"
          ports:
            - containerPort: {{ .Values.functions.shoppingcart.port }}
              name: service
          livenessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 30
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.functions.shoppingcart.name }}
  labels:
    app: {{ include "deployment.fullname" . }}
    component: {{ .Values.functions.shoppingcart.name }}
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 8081
  selector:
    app: {{ include "deployment.fullname" . }}
    component: {{ .Values.functions.shoppingcart.name }}