apiVersion: skaffold/v3
kind: Config
metadata:
  name: sample-scenario-policy-kafka-connect
build:
#  insecureRegistries:
#    - localhost:5001
  local:
    push: true
deploy:
  helm:
#    flags:
#      global: [--debug]
    releases:
    - name: policy-kafka-connect
      chartPath: helm
      setValues:
        kafka.bootstrap_servers: kafka.confluent.svc.cluster.local:9092
        kafka.schema_registry_url: http://schemaregistry.confluent.svc.cluster.local:8081
        mongodb.host: mongodb.mongodb.svc.cluster.local
        mongodb.port: 27017
        mongodb.authDatabase: policiesdb
        mongodb.database: policiesdb
        mongodb.collection: policies
        mongodb.username: user
        mongodb.password: password
