@startuml

database claims_db as "Claims DB\n<<Mongo Db>>>"
database policies_db as "Policies DB\n<<Mongo Db>>>"

queue customers_topic as "customers\n<<Kafka Topic>>"
queue policies_topic as "policies\n<<Kafka Topic>>"
queue claims_topic as "claims\n<<Kafka Topic>>"


claims_db --> claims_topic
policies_db --> policies_topic


claims_db -down[hidden]- claims_topic
policies_db -down[hidden]- policies_topic
policies_db -down[hidden]- customers_topic

customers_topic -right[hidden]- claims_topic
claims_topic -left[hidden]- policies_db
@enduml
